IF OBJECT_ID('PLU', 'U') > 0
	DROP TABLE PLU
GO
-- ==========================================================
-- NAME: PLU
-- Descriprion: Справочник SKU 
-- RELEASE: 
-- Author: 
-- Changelog:
-- ==========================================================
CREATE TABLE DCNT.dbo.PLU (
	PLU_ID T_PLU COLLATE Cyrillic_General_CI_AS NOT NULL,
	PLU_ID_AUTO T_IDENTIFIER_AUTO IDENTITY(1,1) NOT NULL,
	DEPARTMENT_ID T_LOCATION_ID NULL,
	DEPARTMENT_SUB_ID T_LOCATION_ID NULL,
	DEPARTMENT_SECT_ID T_LOCATION_ID NULL,
	VAT_ID T_DOCUMENT_ID NULL,
	BUILDER_ID T_IDENTIFIER NULL,
	IMPOST_ID T_IDENTIFIER NULL,
	ENTERPRISE_ID T_ENTERPRISE_ID COLLATE Cyrillic_General_CI_AS NULL,
	COUNTRY_ID char(6) COLLATE Cyrillic_General_CI_AS NULL,
	STOCK_TYPE T_STOCK_TYPE NOT NULL,
	PLU_NAME T_NAME_LONG2 COLLATE Cyrillic_General_CI_AS NOT NULL,
	PLU_NAME_2 T_NAME_LONG2 COLLATE Cyrillic_General_CI_AS NULL,
	PLU_METHOD T_STOCK_TAKING NOT NULL,
	PLU_BURDEN T_PROCENT NULL,
	PLU_MAX_EXTRA T_PROCENT NULL,
	PLU_VOID T_LIST_VOID NULL,
	PLU_PRICE_METHOD T_FLAG NULL,
	PLU_VAT T_COST NULL,
	PLU_TERM_VAT T_COST NULL,
	PLU_PRICE_HOME T_COST NULL,
	PLU_PRICE_MAIN T_COST NULL,
	PLU_LAST_COST T_COST NULL,
	PLU_LAST_CURR_ID T_CURRENCY_ID NULL,
	SUPPLIER_REFERENCE T_SUPPLIER_REFERENCE COLLATE Cyrillic_General_CI_AS NULL,
	PAYMETH_ID T_IDENTIFIER NULL,
	METRIC_ID T_METRIC_ID NOT NULL,
	PLU_TAX T_PROCENT NULL,
	PLU_NOTE varchar(240) COLLATE Cyrillic_General_CI_AS NULL,
	PLU_NOT_NEGATIVE T_FLAG NOT NULL,
	PLU_CURR_HOME T_CURRENCY_ID NULL,
	PLU_CURR_MAIN T_CURRENCY_ID NULL,
	PLU_PRICEFULL_HOME T_COST NULL,
	PLU_PRICEFULL_MAIN T_COST NULL,
	PLU_LASTFULL_COST T_COST NULL,
	PLU_HOME_OR_MAIN tinyint NULL,
	PLU_IN_PRICE_LIST tinyint DEFAULT 1 NULL,
	[TIMESTAMP] timestamp NULL,
	PLU_STPACK varchar(10) COLLATE Cyrillic_General_CI_AS NULL,
	PLU_DT_REGISTR datetime NULL,
	SERV_COST_MAIN T_COST NULL,
	SERV_COST_HOME T_COST NULL,
	SERV_MANPOWER smallint NULL,
	SERV_MANHOUR T_DOCUMENT_QUAN NULL,
	SERV_NUMB_LICENSE varchar(20) COLLATE Cyrillic_General_CI_AS NULL,
	SERV_DATE_LICENSE T_DATE NULL,
	PLU_IS_PRODUCT T_FLAG NULL,
	PLU_IS_COMPONENT T_FLAG NULL,
	PLU_IS_IMPORT T_FLAG NULL,
	PLU_FORM_PRODUCE T_NAME_SHORT COLLATE Cyrillic_General_CI_AS NULL,
	PLU_MIN_QUAN T_DOCUMENT_QUAN NULL,
	PLU_SHORTNAME T_NAME_SHORT COLLATE Cyrillic_General_CI_AS NULL,
	PLU_IS_PIECE T_FLAG NULL,
	PLU_SN_MANDATORY T_FLAG NULL,
	PLU_MIN_EXTRA T_PROCENT NULL,
	PLU_MAX_QUAN T_DOCUMENT_QUAN NULL,
	PLU_INSERT_DT datetime NULL,
	PLU_URL T_DESCRIBE COLLATE Cyrillic_General_CI_AS NULL,
	PLU_ID_ORD char(15) COLLATE Cyrillic_General_CI_AS NULL,
	PLU_ATX varchar(40) COLLATE Cyrillic_General_CI_AS NULL,
	PLU_DOZA varchar(20) COLLATE Cyrillic_General_CI_AS NULL,
	MNN_ID T_IDENTIFIER NULL,
	PLU_NEED_COLD T_FLAG NULL,
	CONSTRAINT PK_PLU PRIMARY KEY (PLU_ID)
);

 CREATE NONCLUSTERED INDEX FK_REL_ENTERPR_PLU ON DCNT.dbo.PLU (  ENTERPRISE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX FK_REL_IMPOSIT_PLU ON DCNT.dbo.PLU (  IMPOST_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX FK_REL_MNN_PLU ON DCNT.dbo.PLU (  MNN_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX FK_REL_PAYMETH_PLU ON DCNT.dbo.PLU (  PAYMETH_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX FK_REL_PLU_BUILDER ON DCNT.dbo.PLU (  BUILDER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX FK_REL_PLU_COUNTRY ON DCNT.dbo.PLU (  COUNTRY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX FK_REL_PLU_GROUP ON DCNT.dbo.PLU (  DEPARTMENT_ID ASC  , DEPARTMENT_SUB_ID ASC  , DEPARTMENT_SECT_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX FK_REL_PLU_METRIC ON DCNT.dbo.PLU (  METRIC_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX FK_REL_PLU_VAT ON DCNT.dbo.PLU (  VAT_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IND_PLU_NAME ON DCNT.dbo.PLU (  PLU_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IND_PLU_TYPE ON DCNT.dbo.PLU (  STOCK_TYPE ASC  , PLU_NAME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY ] ;
CREATE UNIQUE NONCLUSTERED INDEX IND_PLU_TYPEPLU ON DCNT.dbo.PLU (  STOCK_TYPE ASC  , PLU_ID ASC  )  
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY ] ;
CREATE NONCLUSTERED INDEX [_dta_index_PLU_7_494624805__K12_K1_K3_K7_23] ON DCNT.dbo.PLU (  PLU_NAME ASC  , PLU_ID ASC  , DEPARTMENT_ID ASC  , BUILDER_ID ASC  )  
	INCLUDE ( PLU_LAST_COST ) 
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY ] ;
ALTER TABLE DCNT.dbo.PLU WITH NOCHECK ADD CONSTRAINT CKC_PLU_HOME_OR_MAIN_PLU CHECK (([PLU_HOME_OR_MAIN] = 1 or [PLU_HOME_OR_MAIN] = 0));
ALTER TABLE DCNT.dbo.PLU WITH NOCHECK ADD CONSTRAINT CKC_PLU_IN_PRICE_LIST_PLU CHECK (([PLU_IN_PRICE_LIST] = 0 or [PLU_IN_PRICE_LIST] = 1));


-- DCNT.dbo.PLU внешние включи

ALTER TABLE DCNT.dbo.PLU ADD CONSTRAINT FK_PLU_REL_ENTER_ENTERPRI FOREIGN KEY (ENTERPRISE_ID) REFERENCES DCNT.dbo.ENTERPRISE(ENTERPRISE_ID);
ALTER TABLE DCNT.dbo.PLU ADD CONSTRAINT FK_PLU_REL_IMPOS_IMPOST FOREIGN KEY (IMPOST_ID) REFERENCES DCNT.dbo.IMPOST(IMPOST_ID);
ALTER TABLE DCNT.dbo.PLU ADD CONSTRAINT FK_PLU_REL_PAYME_PAY_METH FOREIGN KEY (PAYMETH_ID) REFERENCES DCNT.dbo.PAY_METHOD(PAYMETH_ID);
ALTER TABLE DCNT.dbo.PLU ADD CONSTRAINT FK_PLU_REL_PLU_B_BUILDER FOREIGN KEY (BUILDER_ID) REFERENCES DCNT.dbo.BUILDER(BUILDER_ID);
ALTER TABLE DCNT.dbo.PLU ADD CONSTRAINT FK_PLU_REL_PLU_C_COUNTRY FOREIGN KEY (COUNTRY_ID) REFERENCES DCNT.dbo.COUNTRY(COUNTRY_ID);
ALTER TABLE DCNT.dbo.PLU ADD CONSTRAINT FK_PLU_REL_PLU_G_DEPARTME FOREIGN KEY (DEPARTMENT_ID,DEPARTMENT_SUB_ID,DEPARTMENT_SECT_ID) REFERENCES DCNT.dbo.DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_SUB_ID,DEPARTMENT_SECT_ID);
ALTER TABLE DCNT.dbo.PLU ADD CONSTRAINT FK_PLU_REL_PLU_M_METRIC FOREIGN KEY (METRIC_ID) REFERENCES DCNT.dbo.METRIC(METRIC_ID);
ALTER TABLE DCNT.dbo.PLU ADD CONSTRAINT FK_PLU_REL_PLU_V_VAT_GROU FOREIGN KEY (VAT_ID) REFERENCES DCNT.dbo.VAT_GROUP(VAT_ID);